Remove Tag::setName
symfony/demo pull request #1357
Opened 2022-08-27 12:32 UTC by chr-hertel

In this case we can move it to constructor

2022-08-27 12:35 UTC, stof requested changes

2022-08-27 12:35 UTC, stof commented on src/Entity/Tag.php
> +use JsonSerializable;
in the Symfony coding standards, we don't add use statements for classes in the global namespace

2022-08-28 01:22 UTC, TheDevick commented
Can we use a `readonly` proprierty in the Entity and keep the `setName` function?

> Why?

Just because sometimes it makes sense to call the constructor with no parameters - `new Tag();` and then call the `setName()` function, so making the code more readable in some cases

2022-08-28 11:04 UTC, chr-hertel commented
I would not agree on having public methods for "just in case..." and within this demo application it is not needed.
And I usually try to avoid those nullable properties if possible.

And no, you cannot combine readonly with setters. That's basically the feature :)

2022-10-28 07:26 UTC, merged

2022-10-28 07:27 UTC, javiereguiluz commented
Christopher, thanks for this nice contribution and sorry it took me so long to merge it.

Please note that while merging I tweaked the new `Tag` entity constructor a bit. See https://github.com/symfony/demo/commit/fbc76bbdf65c61fda8f5ae8478c282f127ead29a Your code is of course perfectly valid, but I think it could look too advanced/unconventional for some folks using this demo application. In the future we might change it again and use your version, but for now I'd prefer to use this more traditional constructor. Thanks!

2022-10-28 07:52 UTC, chr-hertel commented
@javiereguiluz Totally get your point! :) Thanks for coming back to this!